### ISSUE TITLE
RP2040 Support?

### ISSUE THREAD

**Issue by olliecoding321** [MHeironimus/ArduinoJoystickLibrary#253]
It would be great if this supported RPI Pico because of the pico's higher clock and higher input resolution (micro: 10 bit vs Pico: 12 bit)

**Comment by hackingotter** [comment]
I made a port of the library to use USBHID from mbed OS instead of DynamicHID. It was a pretty fundamental change so I couldn't make a merge request to contribute it back to this repository but you can check out my ported version of the library [here](https://github.com/hackingotter/USBJoystickLibrary).
