### ISSUE TITLE
Joystick2 and Joystick3 libraries only appear as single joystick

### ISSUE THREAD

**Issue by jeqbrown** [MHeironimus/ArduinoJoystickLibrary#4]
Hello,

When I use the Joystick2 library, it only appears as a single joystick with 2-axis and 32-buttons. The buttons assigned on the second joystick (Joystick[1]) show as the first joystick (Joystick[0]) button+16... ie- when pressing J2 btn 0 it sends as J1 btn16, J2 btn 4 sends J1 btn20.., etc.. The Joystick3 library does not register ANY joysticks.

I am using Ubuntu 15.04 and jstest-gtk for testing.

**Comment by MHeironimus** [comment]
Take a look at this article and see if it addresses your issue:

http://mheironimus.blogspot.com/2015/09/linux-support-for-arduino-leonardo.html





On Mon, Mar 21, 2016 at 12:36 PM -0700, "jeqbrown" <notifications@github.com> wrote:





Hello,

When I use the Joystick2 library, it only appears as a single joystick with 2-axis and 32-buttons. The buttons assigned on the second joystick (Joystick[1]) show as the first joystick (Joystick[0]) button+16... ie- when pressing J2 btn 0 it sends as J1 btn16, J2 btn 4 sends J1 btn20.., etc.. The Joystick3 library does not register ANY joysticks.

I am using Ubuntu 15.04 and jstest-gtk for testing.

---
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/MHeironimus/ArduinoJoystickLibrary/issues/4

**Comment by jeqbrown** [comment]
Hi Matthew,

Thank you for taking the time to respond. That is exactly what I was looking for! Also, thank you for your work on the Arduino joystick libraries. The library I the perfect solution for my project. It works great in combination with the SNESpaduino library to enable my now "RPi brained" SNES to work with the original controllers. You are the man I send my appreciation for your hard work.

Thank You,

Jerimiah

**Comment by MHeironimus** [comment]
Glad to hear that fixed your problem and that you have found the library useful.


Matt





On Tue, Mar 22, 2016 at 9:38 AM -0700, "jeqbrown" <notifications@github.com> wrote:





Hi Matthew,

Thank you for taking the time to respond. That is exactly what I was looking for! Also, thank you for your work on the Arduino joystick libraries. The library I the perfect solution for my project. It works great in combination with the SNESpaduino library to enable my now "RPi brained" SNES to work with the original controllers. You are the man I send my appreciation for your hard work.

Thank You,

Jerimiah

Sent from my iPhone

> On Mar 22, 2016, at 9:24 AM, Matthew Heironimus <notifications@github.com> wrote:
>
>
>
> Take a look at this article and see if it addresses your issue:
>
> http://mheironimus.blogspot.com/2015/09/linux-support-for-arduino-leonardo.html
>
>
>
>
>
> On Mon, Mar 21, 2016 at 12:36 PM -0700, "jeqbrown" <notifications@github.com> wrote:
>
>
>
>
>
> Hello,
>
> When I use the Joystick2 library, it only appears as a single joystick with 2-axis and 32-buttons. The buttons assigned on the second joystick (Joystick[1]) show as the first joystick (Joystick[0]) button+16... ie- when pressing J2 btn 0 it sends as J1 btn16, J2 btn 4 sends J1 btn20.., etc.. The Joystick3 library does not register ANY joysticks.
>
> I am using Ubuntu 15.04 and jstest-gtk for testing.
>
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/MHeironimus/ArduinoJoystickLibrary/issues/4
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
>


---
