### ISSUE TITLE
Hardware for Driving Controller

### ISSUE THREAD

**Issue by genius613** [MHeironimus/ArduinoJoystickLibrary#84]
## Description of Issue
I am trying to use potentiometers for accelerator and steering and load cell for brake. Can anyone tell me if it possible to use this library to make them appear to a game as a driving controller, and if so, what the wiring and coding would look like?

## Technical Details

Arduino Leonardo 
Windows 10
Arduino IDE Version 1.8.5

**Comment by abqlewis** [comment]
Although I've just started using the library, I'm pretty sure a driving sim wheel and pedals is possible.
As far as the wiring is concerned, the Net has numerous examples (search for sim, wheel, pedals, potentiometer, and even joystick).  You basically hook the ends of a pot to 5v and GND, and hook the wiper to one of the Arduino analog pins (A0, A1 ...).
For the code, there's already a DrivingControllerTest sketch with the library.  Instead of forcing test data  to the Joystick library, do an analogRead of the pins you wired up earlier and pass the result to the Joystick set functions.  Also lookup the Arduino "map" function.  Again, Googling some of these terms will give you a number of examples.
Lastly, most of the pedal sets I've seen (and made) just used a much stiffer spring and limited travel for the brake.  I found most load cells don't have the travel of a real brake pedal, and you risk putting more pressure/stress on the pedal assembly.
