### ISSUE TITLE
joystick not detected

### ISSUE THREAD

**Issue by R3dThek** [MHeironimus/ArduinoJoystickLibrary#88]
Hello,

i try to make a steering wheel, but my arduino pro micro doesn't appear as joystick on windows 10 and only as board without joystick library, but on linux it's working.

Any idea ?

Edit: I changed "JOYSTICK_TYPE_MULTI_AXIS" by "JOYSTICK_TYPE_JOYSTICK" and it's working, but i don't know why "JOYSTICK_TYPE_MULTI_AXIS" don't work on windows 10

**Comment by legomolina** [comment]
Same here, I'm trying to code a potentiometer as a throttle but I can't with:
`Joystick_ Joystick(JOYSTICK_DEFAULT_REPORT_ID, JOYSTICK_TYPE_MULTI_AXIS, 0, 0, false, false, false, false, false, false, false, true, false, false, false);`

If instead of MULTI_AXIS I put GAMEPAD, Windows 10 recognices it as a GamePad.

**Comment by R3dThek** [comment]
you can use "JOYSTICK_TYPE_JOYSTICK"

**Comment by MHeironimus** [comment]
I added the ability to select the HID input device type to address issues like this. If a particular device type is not working for your application, I suggest trying a different one. 

- `uint8_t joystickType` - Default: `JOYSTICK_TYPE_JOYSTICK` or `0x04` - Indicates the HID input device type. Supported values:
  - `JOYSTICK_TYPE_JOYSTICK` or `0x04` - Joystick 
  - `JOYSTICK_TYPE_GAMEPAD` or `0x05` - Gamepad
  - `JOYSTICK_TYPE_MULTI_AXIS` or `0x08` - Multi-axis Controller 

The following is an excerpt from the *Universal Serial Bus (USB) HID Usage Tables* document (1/21/2005 - Version 1.12):

**Joystick**
CA – A manual control or cursor device. A joystick minimally consists of two variable axes (X and Y) and two buttons. A joystick is typically a rotational motion sensor. However, for legacy reasons, it is defined using linear axes.
Traditionally, a joystick driver applies its own scaling to values returned from a joystick. That is, the driver simply linearizes and translates the range of values generated by the stick into normalized values between 0 and 64K, where 32K is centered. The application (game) then interprets the normalized values as necessary. Because of this, joysticks normally do not declare Units or Physical Minimum and Physical Maximum values for their axes. Depending on the driver, these items may be ignored if they are declared.

**Game Pad**
CA – A manual control or cursor device. A game pad minimally consists of a thumb-activated rocker switch that controls two axes (X and Y) and has four buttons. The rocker switch consists of four contact closures for up, down, right, and left.

**Multi-axis Controller**
CA - An input device used to orient eyepoints and or objects in 3 dimensional space. A Multi-axis Controller typically consists of six, variable axes (X, Y,Z, Rx, Ry and Rz) and is used by CAD/digital content creation applications for model manipulation and visualization in 3D space. The device may incorporate zero or more buttons.
